### ISSUE TITLE
AdHocStarter ".start()" docs update

### ISSUE THREAD

**Issue by jblayneyXpanxion** [chrisgleissner/spring-batch-rest#12]
Looks like AdHocStarter takes a parameter "JobConfig" which is a member class of this library.

Docs state that this start() call takes generic Spring Batch Param types:

String, Job

Any information on how to correctly configure & use the JobConfig as a parameter to call start() would be very much appreciated.

Thanks for any help or clarification!

**Comment by chrisgleissner** [comment]
Hello,

You can find an example of how to use this API at
https://github.com/chrisgleissner/spring-batch-rest/blob/master/example/quartz-api/src/test/java/com/github/chrisgleissner/springbatchrest/example/quartz/PersonJobTest.java

Have a look at how the JobConfig is built in that class and maybe use this
as a starting point.

Thanks
Christian
