### ISSUE TITLE
Question: Quartz Group Name

### ISSUE THREAD

**Issue by jblayneyXpanxion** [chrisgleissner/spring-batch-rest#14]
The Quarz Group Name seems to be hard-coded to "group".

How does one change this?

I assume since its exposed through the rest API there is some way to override it.. but looking at the class I'm sort of dense when it comes to how to do it.

Thanks for any help!

**Comment by chrisgleissner** [comment]
Hi, is this question still relevant or did you find a solution? If not, I can investigate. Thanks

**Comment by jblayneyXpanxion** [comment]
I made the quartz group "null" rather than "group". As passing a null will use the default group. It can also be overridden by the user.
