### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by nicolovergari** [chrisgleissner/spring-batch-rest#19]
Hi, do you have any intention of setting up some kind of authentication to enter the Swagger page?

**Comment by chrisgleissner** [comment]
Hi, 

you can secure the Swagger page by adding the Spring Boot security starter to your project:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
```

I intentionally didn't configure it as part of `spring-batch-rest` since security configurations vary wildly and it seemed out of scope for this library. 

Thanks
