### ISSUE TITLE
ERROR 500 with stacktrace when a job is lauched more than once.

### ISSUE THREAD

**Issue by tisseurdetoile** [chrisgleissner/spring-batch-rest#3]
Hello, 
when I start a job with the same parameter it cause an error 500.
I think It would be nice not to fail in this case. but catch the error and display it.

Error on the client side.
```json
{
  "timestamp": "2018-12-22T13:54:36.839+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Failed to start personJob",
  "trace": "java.lang.RuntimeException: Failed to start personJob\n\tat com.github.chrisgleissner.springbatchrest.util.adhoc.AdHocStarter.start(AdHocStarter.java:53)\n\tat com.github.chrisgleissner.springbatchrest.api.jobexecution.JobExecutionService.launch(JobExecutionService.java:74)\n...",
 "path": "/jobExecutions"
}
```
Error on the server
```
rg.springframework.batch.core.repository.JobInstanceAlreadyCompleteException: A job instance already exists and is complete for parameters={upperCase=true, additionalProp3=stringz, additionalProp2=string}.  If you want to run this job again, change the parameters.
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:132) ~[spring-batch-core-4.1.0.RELEASE.jar:4.1.0.RELEASE]
...
```

**Comment by chrisgleissner** [comment]
Hi,

Thanks for your message.

One way of resolving this would be to transparently add a unique value
(e.g. a UUID) to the parameters of a job. This could be done inside the
AdhocScheduler.

For example, if you submit the same job with the same parameters twice, the
second invocation would succeed since Spring Batch would regard the second
invocation as a new job instance due to the transparently added UUID job
parameter.

Please let me know whether this would work for you and I can add this
feature.

Thanks
Christian

**Comment by chrisgleissner** [comment]
Hello,

I have fixed this issue.

You will now see the root exception's message in the response returned to
the client which should make it clearer why a certain job invocation failed.

Also, I added a unique ID (a random UUID) to the job parameters which
allows you to retrigger the same job with the same parameters multiple
times. If you don't want this behaviour, it can be disabled via the Spring
com.github.chrisgleissner.springbatchrest.addUniqueJobParameter property.

You can find these two changes in release 1.2.1 which I just cut. It should
be available from Maven Central within ca. 10h.

Kind Regards
Christian Gleissner
_____________________________________________________________
chrisgleissner@gmail.com

**Comment by chrisgleissner** [comment]
Fixed in 1.2.1

**Comment by tisseurdetoile** [comment]
Thanks, your pretty kick (too for me).

Sorry I don't make myself clear, for me the problem was not to launch a job with the same parameter (To achieve that I use RunIdIncrementer()).
But JobParametersInvalidException, JobInstanceAlreadyCompleteException and JobExecutionAlreadyRunningException are not Error 500 in my opinion (maybe 412 for the JobParametersInvalidException),  as you catch all Exception in JobExecutionService.jobExecution then All this exeption are trapped in Runtime exeption and end with a massive an unsollicited stack trace.

Sorry for not be clear at the first time.

**Comment by chrisgleissner** [comment]
Hi,

I will work on mapping these exceptions to more appropriate http status
codes. Thanks for your suggestion.

For the time being, as of 2.1.2, you will now receive the root exception
message in the response body.

I will cut a new release once the mapping above is done, but it may be
until after the new year. If you would like to send me a pull request,
please let me know and I will merge it.

Thanks
Christian

**Comment by chrisgleissner** [comment]
Map Spring Batch exceptions such as JobParametersInvalidException, JobInstanceAlreadyCompleteException and JobExecutionAlreadyRunningException to an appropriate HTTP status code.

**Comment by chrisgleissner** [comment]
Fixed exception to status code mapping in release 1.2.2 and updated docs.
