### ISSUE TITLE
mariadb backend

### ISSUE THREAD

**Issue by kenhutaiwan** [chrisgleissner/spring-batch-rest#4]
Hi Chris:

Thanks for your open-source work of spring-batch-rest.

I fork it on the github as a new project and then I make it compatible with spring boot 1.5.3(the current version we used for work). After I plug it in an existed spring batch/boot application with mariadb backend, when I visit http://localhost:8130/jobs, I expect I will get the jobs stored in mariadb(ie: BATCH_JOB_INSTANCE), but I get no one.

Can you please give me some advices to make this work? 
Thanks in advance.

**Comment by kenhutaiwan** [comment]
I figure it out.
Use JobExplorer in JobService class, and then configure a JobExplorer bean in my sprint boot/batch application:

    @Bean
    public JobExplorer jobExplorer(DataSource dataSource) throws Exception {
        final JobExplorerFactoryBean factory = new JobExplorerFactoryBean();
        factory.setDataSource(dataSource);
        //factory.setTablePrefix("abs.BATCH_");
        factory.afterPropertiesSet();
        return factory.getObject();
    }

**Comment by chrisgleissner** [comment]
Hi Ken,

Thanks for your email and glad you figured out how to integrate it in your
project.

Best wishes
Christian
