### ISSUE TITLE
Does not run in spring-boot 2.2.0

### ISSUE THREAD

**Issue by bibibiu2017** [chrisgleissner/spring-batch-rest#5]
I don't know whether this is an issue or a feature request

Spring boot 2.2.0 uses  HATEOAS to version 1.0.0 which introduced [breaking changes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#spring-hateoas-10) to HATEOAS.

**Comment by chrisgleissner** [comment]
Hi bibibiu2017, 

thanks for letting me know. It's more of a feature request since the issue was introduced by a new version Spring Boot which Spring Batch Rest doesn't support yet. 

I'll investigate this in the next few days to see what needs to be done to ensure compatibility with Spring Boot 2.2.x.

Thanks, 
Christian

**Comment by chrisgleissner** [comment]
Will be solved using https://github.com/chrisgleissner/spring-batch-rest/pull/6

**Comment by bibibiu2017** [comment]
Hi,
Any updates on this?

**Comment by chrisgleissner** [comment]
Hi,

I have been very busy the last few weeks but it should be a straightforward
fix and I hope to tackle it in the next few weeks.

If it is urgent, I left a link on the jira that shows what needs to be done
and I would be happy to merge in a pull request.

Thanks
Christian

**Comment by chrisgleissner** [comment]
I upgraded to Spring Boot 2.2 and thus HATEOAS 1.0, but a merge of this feature into master is currently blocked by an autowiring issue related to Spring Boot 2.2, HATEOAS 1.0, and Springfox 2.9.2 as discussed in https://github.com/spring-projects/spring-hateoas/issues/1094. This will require further research.

**Comment by chrisgleissner** [comment]
I've upgraded to Spring Boot 2.2.4.RELEASE and also switched from Springfox to Springdoc which relies on OpenAPI 3: 

`com.github.chrisgleissner:spring-batch-rest-api:1.3.0`

**Comment by bibibiu2017** [comment]
> I upgraded to Spring Boot 2.2 and thus HATEOAS 1.0 in a feature branch, but a merge of this change into master is currently blocked by an autowiring issue related to Spring Boot 2.2, HATEOAS 1.0, and Springfox 2.9.2 as discussed in [spring-projects/spring-hateoas#1094](https://github.com/spring-projects/spring-hateoas/issues/1094).
> 
> The error manifests itself during context wiring and breaks most of the tests with:
> 
> ```
> ***************************
> APPLICATION FAILED TO START
> ***************************
> Description:
> Parameter 0 of method linkDiscoverers in org.springframework.hateoas.config.HateoasConfiguration required a single bean, but 17 were found:
> 	- modelBuilderPluginRegistry: defined in null
> 	- modelPropertyBuilderPluginRegistry: defined in null
> 	- typeNameProviderPluginRegistry: defined in null
> 	- syntheticModelProviderPluginRegistry: defined in null
> 	- documentationPluginRegistry: defined in null
> 	- apiListingBuilderPluginRegistry: defined in null
> 	- operationBuilderPluginRegistry: defined in null
> 	- parameterBuilderPluginRegistry: defined in null
> 	- expandedParameterBuilderPluginRegistry: defined in null
> 	- resourceGroupingStrategyRegistry: defined in null
> 	- operationModelsProviderPluginRegistry: defined in null
> 	- defaultsProviderPluginRegistry: defined in null
> 	- pathDecoratorRegistry: defined in null
> 	- apiListingScannerPluginRegistry: defined in null
> 	- relProviderPluginRegistry: defined by method 'relProviderPluginRegistry' in class path resource [org/springframework/hateoas/config/HateoasConfiguration.class]
> 	- linkDiscovererRegistry: defined in null
> 	- entityLinksPluginRegistry: defined by method 'entityLinksPluginRegistry' in class path resource [org/springframework/hateoas/config/WebMvcEntityLinksConfiguration.class]
> Action:
> Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
> ```
> 
> This will need further investigation.

This is what I faced when I tried the upgrade.

**Comment by chrisgleissner** [comment]
Hi @bibibiu2017, 

The issue you raised should be resolved now since Spring Batch Rest now uses Spring Boot 2.2.

I am not sure how you are using Spring Batch Rest, but in case you are pulling it in as a released dependency, you may want to upgrade it to version 1.3.0 which I released yesterday. I fixed the clash between HATEOAS 1.0 and Springfox 2.9.2 by swapping the latter for Springdoc which seems better maintained than Springfox at the moment. All tests work. In case you are using it another way, you may want to try to get rid of Springfox. 

Thanks
Christian
