### ISSUE TITLE
Disable quartz

### ISSUE THREAD

**Issue by jmformenti** [chrisgleissner/spring-batch-rest#7]
Hello,

  Is it possible to disable quartz? I just want to execute jobs by api request

**Comment by chrisgleissner** [comment]
Hi,

thanks for your suggestion. I am currently working on this and should have a new release soon.

Christian

**Comment by chrisgleissner** [comment]
This has now been done and a new release 1.4.0 has been cut. Details on the split between core API and Quarty-enabled API are in the updated README.md.

**Comment by jmformenti** [comment]
Thanks! works like a charm

**Comment by chrisgleissner** [comment]
Hello,

glad it worked. If you need anything else done, please let me know.
Merge requests always welcome, of course. :-)

Thanks
Christian
